package org.yhwang.csye6225.courseservice5.datamodel;

import com.amazonaws.services.dynamodbv2.datamodeling.*;

import javax.xml.bind.annotation.XmlRootElement;
import java.util.List;

@XmlRootElement//map a class to xml
@DynamoDBTable(tableName ="board")
public class Board {
    private String Id;
    private String boardId;
    private String courseId;
    private List<String> announcements;

    public Board() {
    }

    @DynamoDBHashKey(attributeName = "Id")
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return Id;
    }

    public void setId(String id) {
        Id = id;
    }

    @DynamoDBIndexHashKey(attributeName = "boardId", globalSecondaryIndexName = "boardId-index")
    public String getBoardId() {
        return boardId;
    }

    public void setBoardId(String boardId) {
        this.boardId = boardId;
    }

    @DynamoDBAttribute(attributeName = "courseId")
    public String getCourseId() {
        return courseId;
    }

    public void setCourseId(String courseId) {
        this.courseId = courseId;
    }

    @DynamoDBAttribute(attributeName = "announcements")
    public List<String> getAnnouncements() {
        return announcements;
    }

    public void setAnnouncements(List<String> announcements) {
        this.announcements = announcements;
    }

    @Override
    public String toString() {
        return "Board{" +
                "Id='" + Id + '\'' +
                ", boardId='" + boardId + '\'' +
                ", courseId='" + courseId + '\'' +
                ", announcements=" + announcements +
                '}';
    }
}
