package org.yhwang.csye6225.courseservice5.datamodel;
import com.amazonaws.services.dynamodbv2.datamodeling.*;

import javax.xml.bind.annotation.XmlRootElement;
import java.util.*;

@XmlRootElement
@DynamoDBTable(tableName ="course")
public class Course {


    private String Id;
    private String courseId;
    //private String courseName;
    //private List<Lecture> lectures;
    private String boardId;
    private List<String> enrolledStudent;
    private String TAId;
    private String professorId;

    public Course(){}

    public Course(String courseId, String courseName) {
        this.courseId = courseId;
       // this.courseName = courseName;
      //  this.lectures = null;
        this.boardId = null;
        this.enrolledStudent = null;
        this.TAId = null;
        this.professorId = null;
    }

    @DynamoDBHashKey(attributeName = "Id")
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return Id;
    }

    public void setId(String id) {
        Id = id;
    }

   // @DynamoDBHashKey(attributeName = "courseId")
    @DynamoDBIndexHashKey(attributeName = "courseId")
    public String getCourseId() {
        return courseId;
    }

    public void setCourseId(String courseId) {
        this.courseId = courseId;
    }
//
//    @DynamoDBAttribute(attributeName = "courseName")
//    public String getCourseName() {
//        return courseName;
//    }
//
//    public void setCourseName(String courseName) {
//        this.courseName = courseName;
//    }
//
//    @DynamoDBAttribute(attributeName = "lectures")
//    public List<Lecture> getLectures() {
//        return lectures;
//    }
//
//    public void setLectures(List<Lecture> lectures) {
//        this.lectures = lectures;
//    }

    @DynamoDBAttribute(attributeName = "boardId")
    public String getBoard() {
        return boardId;
    }

    public void setBoard(String boardId) {
        this.boardId = boardId;
    }

    @DynamoDBAttribute(attributeName = "enrolledStudent")
    public List<String> getEnrolledStudent() {
        return enrolledStudent;
    }

    public void setEnrolledStudent(List<String> enrolledStudent) {
        this.enrolledStudent = enrolledStudent;
    }

    @DynamoDBAttribute(attributeName = "TAId")
    public String getTA() {
        return TAId;
    }

    public void setTA(String TAId) {
        this.TAId = TAId;
    }

    @DynamoDBAttribute(attributeName = "professorId")
    public String getAssociatedProfessor() {
        return professorId;
    }

    public void setAssociatedProfessor(String professorId) {
        this.professorId = professorId;
    }
}
